# Generated by Django 5.0.1 on 2024-01-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_address_id_alter_cart_id_alter_cartitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
