# Generated by Django 5.0.1 on 2024-02-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_wishlist_date_added_remove_wishlist_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='cart',
            new_name='wishlist',
        ),
    ]
