# Generated by Django 5.0.1 on 2024-01-15 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='category/banner/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category/icon/')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('attributes', models.ManyToManyField(to='products.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(default=0)),
                ('mrp', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='product/videos/')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
