# Generated by Django 5.0.1 on 2024-02-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
